# Azure Pipelines for Makefile-based Node.js app
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x'
  BUILD_ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

steps:
# 1. Checkout code
- checkout: self
  clean: true

# 2. Set up Node.js (for running node or tests)
- task: UseNode@1
  inputs:
    version: $(NODE_VERSION)
  displayName: 'Use Node.js $(NODE_VERSION)'

# 3. Run Makefile targets
# Adjust targets below based on what exists in your Makefile (e.g., make lint, make build, make test)
- script: |
    echo "🧰 Running Makefile targets..."
    make lint || echo "Skipping lint (not defined)"
    make build || echo "Skipping build (not defined)"
    make test || echo "Skipping test (not defined)"
  displayName: 'Run Makefile build/test'

# 4. Optional — Archive build output
- task: CopyFiles@2
  displayName: 'Copy build output'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !node_modules/**
    TargetFolder: '$(BUILD_ARTIFACT_STAGING_DIR)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(BUILD_ARTIFACT_STAGING_DIR)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
